# Titanic Data Cleaning & Preprocessing

This notebook demonstrates a comprehensive data cleaning and preprocessing pipeline for the famous Titanic dataset. The goal is to transform the raw dataset into a clean, structured, and analysis-ready format, addressing common data quality issues such as missing values, incorrect data types, and duplicate records. This project is designed to be beginner-friendly, suitable for internship submissions, and ready for GitHub upload.

## 1. Dataset Overview

This section covers the necessary library imports and loading the `Titanic-Dataset.csv` file into a pandas DataFrame. We'll then perform a preliminary overview to understand its basic structure, including its shape, column names, and a quick look at the first few rows.

In [55]:
# Import the pandas library for efficient data manipulation
import pandas as pd

# Define the file path for the dataset. The file is expected to be in the current directory.
file_path = 'Titanic-Dataset.csv'

# Load the dataset into a pandas DataFrame
try:
    df = pd.read_csv(file_path)
    print(f"Dataset '{file_path}' loaded successfully.")
except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found. Please ensure it's uploaded to the current directory.")
    df = None # Set df to None to prevent subsequent operations from failing

Dataset 'Titanic-Dataset.csv' loaded successfully.

In [56]:
if df is not None:
    # Display the shape of the dataset (number of rows, number of columns)
    print("\n--- Dataset Shape ---")
    print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

--- Dataset Shape ---
Rows: 891, Columns: 12

In [57]:
if df is not None:
    # Display all column names to understand available features
    print("\n--- Column Names ---")
    print(df.columns.tolist())

--- Column Names ---
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [58]:
if df is not None:
    # Display the first 5 rows to get a quick glimpse of the data content and format
    print("\n--- First 5 Rows of the Dataset ---")
    display(df.head())

--- First 5 Rows of the Dataset ---

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 2. Dataset Information

Understanding the data types and non-null counts for each column is crucial for identifying potential data quality issues, such as missing values or incorrectly assigned data types. The `df.info()` method provides a concise summary of the DataFrame.

In [59]:
if df is not None:
    print("--- Dataset Information (df.info()) ---")
    # The .info() method prints a summary of the DataFrame, including the index dtype and column dtypes,
    # non-null values, and memory usage.
    df.info()

    print("\nExplanation:")
    print("  - 'PassengerId', 'Survived', 'Pclass', 'SibSp', 'Parch', 'Fare' are integers or floats.")
    print("  - 'Name', 'Sex', 'Ticket', 'Cabin', 'Embarked' are object (string) types.")
    print("  - Notice the 'Age', 'Cabin', and 'Embarked' columns have fewer non-null entries than the total rows (891),")
    print("    indicating the presence of missing values that need to be addressed.")

--- Dataset Information (df.info()) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Explanation:
  - 'PassengerId', 'Survived', 'Pclass', 'SibSp', 'Parch', 'Fare' are integers or floats.
  - 'Name', 'Sex', 'Ticket', 'Cabin', 'Embarked' are object (string) types.
  - Notice the 'Age', 'Cabin', and 'Embarked' columns have fewer non-null entries than the total rows (891),
    indicating the presence of missing values that need to be addressed.

## 3. Statistical Summary

A statistical summary provides key descriptive statistics for numerical columns, offering insights into the distribution, central tendency, and spread of the data. This helps in detecting outliers or unusual patterns.

In [60]:
if df is not None:
    print("--- Statistical Summary (df.describe()) ---")
    # The .describe() method generates descriptive statistics that summarize the central tendency,
    # dispersion, and shape of a dataset's distribution, excluding NaN values.
    # This is applied to numerical columns by default.
    display(df.describe())

    print("\nExplanation of Statistical Summary:")
    print("  - `count`: Number of non-null observations. Confirms missing values in 'Age'.")
    print("  - `mean`, `std`: Average value and standard deviation. Useful for understanding data spread.")
    print("  - `min`, `max`: Minimum and maximum values. Can help identify extreme values or outliers.")
    print("  - `25%`, `50%` (median), `75%`: Quartiles. Provide insight into the distribution of data. For example, the median age is around 28-29.")

--- Statistical Summary (df.describe()) ---

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

Explanation of Statistical Summary:
  - `count`: Number of non-null observations. Confirms missing values in 'Age'.
  - `mean`, `std`: Average value and standard deviation. Useful for understanding data spread.
  - `min`, `max`: Minimum and maximum values. Can help identify extreme values or outliers.
  - `25%`, `50%` (median), `75%`: Quartiles. Provide insight into the distribution of data. For example, the median age is around 28-29.

## 4. Missing Value Analysis

Identifying the exact count and percentage of missing values per column is the first step in deciding an appropriate strategy for handling them. This analysis highlights which columns require attention.

In [61]:
if df is not None:
    print("--- Missing Values Analysis ---")
    # Calculate the number of missing values for each column
    missing_values_count = df.isnull().sum()
    # Calculate the percentage of missing values for each column
    missing_values_percentage = (df.isnull().sum() / len(df)) * 100

    # Create a DataFrame to display this information clearly
    missing_info_df = pd.DataFrame({
        'Missing Count': missing_values_count,
        'Missing Percentage (%)': missing_values_percentage
    })

    # Filter to show only columns with missing values and sort by count
    missing_info_df = missing_info_df[missing_info_df['Missing Count'] > 0].sort_values(by='Missing Count', ascending=False)

    if not missing_info_df.empty:
        print("Columns with Missing Values:")
        display(missing_info_df)
    else:
        print("No missing values found in the dataset.")

--- Missing Values Analysis ---
Columns with Missing Values:

          Missing Count  Missing Percentage (%)
Cabin               687               77.104377
Age                 177               19.865320
Embarked              2                0.224467

## 5. Handling Missing Values

Based on the analysis, we will implement strategies to handle missing values professionally:
-   **Age**: Impute with the median, as it's less sensitive to outliers than the mean.
-   **Embarked**: Impute with the mode, as it's a categorical feature.
-   **Cabin**: Drop this column entirely due to a very high percentage of missing values (approximately 77%), which makes imputation unreliable and the column potentially uninformative.

In [62]:
if df is not None:
    # --- Before Handling Missing Values ---
    print("--- Missing Values Before Handling ---")
    missing_before_handling = df.isnull().sum()
    display(missing_before_handling[missing_before_handling > 0])

    # 1. Fill 'Age' with the median value
    # Median is robust to outliers, making it a good choice for numerical distributions that might be skewed.
    age_median_value = df['Age'].median()
    df['Age'].fillna(age_median_value, inplace=True)
    print(f"\n'Age' column missing values filled with median: {age_median_value:.2f}")

    # 2. Fill 'Embarked' with the mode value
    # Mode is the most appropriate imputation strategy for categorical columns.
    embarked_mode_value = df['Embarked'].mode()[0] # .mode() returns a Series, so [0] selects the first mode
    df['Embarked'].fillna(embarked_mode_value, inplace=True)
    print(f"'Embarked' column missing values filled with mode: '{embarked_mode_value}'")

    # 3. Drop 'Cabin' column due to excessive missing values
    # A large number of missing values often means the column lacks sufficient information.
    if 'Cabin' in df.columns:
        df.drop('Cabin', axis=1, inplace=True)
        print("'Cabin' column dropped due to excessive missing values.")

--- Missing Values Before Handling ---

Age         177
Cabin       687
Embarked      2
dtype: int64

'Age' column missing values filled with median: 28.00
'Embarked' column missing values filled with mode: 'S'
'Cabin' column dropped due to excessive missing values.

/tmp/ipykernel_2600/2958770858.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(age_median_value, inplace=True)
/tmp/ipykernel_2600/2958770858.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(embarked_mode_value, inplace=True)

In [63]:
if df is not None:
    # --- After Handling Missing Values ---
    print("\n--- Missing Values After Handling ---")
    missing_after_handling = df.isnull().sum()
    if missing_after_handling.sum() == 0:
        print("All specified missing values have been handled successfully. No missing values remain in the processed columns.")
    else:
        display(missing_after_handling[missing_after_handling > 0])

--- Missing Values After Handling ---
All specified missing values have been handled successfully. No missing values remain in the processed columns.

## 6. Duplicate Removal

Duplicate records can lead to biased statistical analysis and machine learning models. This step identifies and removes any exact duplicate rows to ensure the integrity of our dataset.

In [64]:
if df is not None:
    # --- Check for duplicate records ---
    initial_rows_duplicates = df.shape[0]
    duplicates_count = df.duplicated().sum()
    print(f"--- Duplicate Records Before Removal ---")
    print(f"Number of duplicate rows found: {duplicates_count}\n")

    # --- Remove duplicates if present ---
    if duplicates_count > 0:
        df.drop_duplicates(inplace=True)
        print(f"Successfully removed {duplicates_count} duplicate rows.")
    else:
        print("No duplicate rows found to remove.")

    # --- Show before and after counts ---
    final_rows_duplicates = df.shape[0]
    print("\n--- Duplicate Records After Removal ---")
    print(f"Number of rows after removing duplicates: {final_rows_duplicates}")
    print(f"Number of duplicate rows remaining: {df.duplicated().sum()}")
    print(f"Total rows removed: {initial_rows_duplicates - final_rows_duplicates}")

--- Duplicate Records Before Removal ---
Number of duplicate rows found: 0

No duplicate rows found to remove.

--- Duplicate Records After Removal ---
Number of rows after removing duplicates: 891
Number of duplicate rows remaining: 0
Total rows removed: 0

## 7. Data Type Conversion

Optimizing data types can lead to significant memory savings and improved performance for certain operations. Categorical features like 'Sex' and 'Embarked' are best represented with the `category` data type.

In [65]:
if df is not None:
    print("--- Data Types Before Conversion ---")
    display(df.dtypes)

--- Data Types Before Conversion ---

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [66]:
if df is not None:
    # Convert 'Sex' to 'category'
    # 'category' type is suitable for columns with a limited number of unique values, offering memory efficiency.
    if 'Sex' in df.columns:
        df['Sex'] = df['Sex'].astype('category')
        print("\n'Sex' column converted to 'category'.")

    # Convert 'Embarked' to 'category'
    if 'Embarked' in df.columns:
        df['Embarked'] = df['Embarked'].astype('category')
        print("'Embarked' column converted to 'category'.")

'Sex' column converted to 'category'.
'Embarked' column converted to 'category'.

In [67]:
if df is not None:
    print("\n--- Data Types After Conversion ---")
    display(df.dtypes)

    print("\nExplanation of changes:")
    print("  - 'Sex' and 'Embarked' have been converted from 'object' to 'category'.")
    print("  - This conversion is beneficial for memory optimization and can speed up operations on these columns.")

--- Data Types After Conversion ---

PassengerId       int64
Survived          int64
Pclass            int64
Name             object
Sex            category
Age             float64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Embarked       category
dtype: object

Explanation of changes:
  - 'Sex' and 'Embarked' have been converted from 'object' to 'category'.
  - This conversion is beneficial for memory optimization and can speed up operations on these columns.

## 8. Renaming Columns

Renaming columns to more intuitive and consistent names enhances code readability and makes the dataset easier to work with, especially for new collaborators or future analysis.

In [68]:
if df is not None:
    print("--- Column Names Before Renaming ---")
    print(df.columns.tolist())

--- Column Names Before Renaming ---
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Embarked']

In [69]:
if df is not None:
    # Rename 'PassengerId' to 'Passenger_ID' and 'Pclass' to 'Passenger_Class'
    # Using a dictionary for renaming is a clear and concise way to handle multiple renames.
    df.rename(columns={
        'PassengerId': 'Passenger_ID',
        'Pclass': 'Passenger_Class'
    }, inplace=True)
    print("\nColumns 'PassengerId' and 'Pclass' renamed to 'Passenger_ID' and 'Passenger_Class' respectively.")

Columns 'PassengerId' and 'Pclass' renamed to 'Passenger_ID' and 'Passenger_Class' respectively.

In [70]:
if df is not None:
    print("\n--- Column Names After Renaming ---")
    print(df.columns.tolist())

--- Column Names After Renaming ---
['Passenger_ID', 'Survived', 'Passenger_Class', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Embarked']

## 9. Final Dataset Verification

After completing all cleaning and preprocessing steps, a final verification is essential to ensure the dataset is in the expected state and ready for downstream tasks such as analysis or model training.

In [71]:
if df is not None:
    print("--- Final Dataset Verification ---")

    # Show final shape to confirm row/column changes after cleaning
    print(f"\nFinal Dataset Shape: {df.shape}")

    # Show updated column names
    print("\nUpdated Column Names:")
    print(df.columns.tolist())

    # Display the first 5 rows of the cleaned dataset
    print("\nFirst 5 Rows of Cleaned Dataset:")
    display(df.head())

    # Show final df.info() to confirm data types and absence of missing values
    print("\nFinal Dataset Information (df.info()):")
    df.info()

--- Final Dataset Verification ---

Final Dataset Shape: (891, 11)

Updated Column Names:
['Passenger_ID', 'Survived', 'Passenger_Class', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Embarked']

First 5 Rows of Cleaned Dataset:

,Passenger_ID,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

Final Dataset Information (df.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Passenger_ID     891 non-null    int64
 1   Survived         891 non-null    int64
 2   Passenger_Class  891 non-null    int64
 3   Name             891 non-null    object
 4   Sex              891 non-null    category
 5   Age              891 non-null    float64
 6   SibSp            891 non-null    int64
 7   Parch            891 non-null    int64
 8   Ticket           891 non-null    object
 9   Fare             891 non-null    float64
 10  Embarked         891 non-null    category
dtypes: category(2), float64(2), int64(5), object(2)
memory usage: 64.8+ KB

## 10. Save Cleaned Dataset

Saving the cleaned dataset is a critical step. This ensures that the preprocessing efforts are preserved, allowing for quick access to the prepared data without needing to re-run the entire cleaning pipeline. This `Cleaned_Titanic_Dataset.csv` can then be used for further analysis or model building.

In [72]:
if df is not None:
    # Define the output file path for the cleaned dataset
    output_file_name = 'Cleaned_Titanic_Dataset.csv'

    # Save the DataFrame to a CSV file. index=False prevents pandas from writing the DataFrame index as a column.
    df.to_csv(output_file_name, index=False)
    print(f"\nCleaned dataset successfully saved as '{output_file_name}'.")
    print("This file is now ready for further analysis or machine learning model development.")

Cleaned dataset successfully saved as 'Cleaned_Titanic_Dataset.csv'.
This file is now ready for further analysis or machine learning model development.

## 11. Conclusion

This project successfully completed a comprehensive data cleaning and preprocessing workflow for the Titanic dataset, transforming raw data into an analysis-ready format. The key steps undertaken include:

*   **Initial Exploration**: Conducted a thorough examination of the dataset's structure, column names, initial rows, and data types to identify data quality issues.
*   **Missing Values Handled**: Strategically addressed missing values by imputing 'Age' with its median and 'Embarked' with its mode. The 'Cabin' column was dropped due to an overwhelming number of missing entries, rendering it impractical for imputation.
*   **Duplicate Records Removed**: Identified and eliminated duplicate rows, ensuring each observation is unique and preventing potential biases in subsequent analyses.
*   **Data Types Converted**: Optimized data types by converting 'Sex' and 'Embarked' to more memory-efficient 'category' types, improving performance and resource utilization.
*   **Columns Renamed**: Improved clarity and consistency by renaming 'PassengerId' to 'Passenger_ID' and 'Pclass' to 'Passenger_Class'.
*   **Final Verification**: Performed a final check on the dataset's shape, column integrity, and data types to confirm all preprocessing steps were executed correctly.
*   **Cleaned Dataset Saved**: The thoroughly processed dataset was saved as `Cleaned_Titanic_Dataset.csv`, making it readily available for predictive modeling, statistical analysis, or visualization tasks.

This robust preprocessing pipeline ensures the dataset is now clean, consistent, and well-prepared, significantly enhancing its reliability for any downstream data science endeavors. This notebook serves as an excellent example of standard practices in data preprocessing, suitable for internship submissions and a valuable addition to a data science portfolio.

# Titanic Dataset: Data Cleaning and Preprocessing Project

This notebook demonstrates a comprehensive data cleaning and preprocessing pipeline for the famous Titanic dataset. The goal is to prepare the dataset for further analysis or machine learning model building by handling missing values, removing duplicates, correcting data types, and renaming columns. This project is designed to be beginner-friendly, suitable for internship submissions, and ready for GitHub upload.

## 1. Dataset Overview

This section handles the initial setup, including importing necessary libraries and loading the dataset. We'll then perform a preliminary overview to understand its basic structure, including its shape, column names, and a quick look at the first few rows.

In [73]:
# Import the pandas library for efficient data manipulation
import pandas as pd

# Define the file path for the dataset. The file is expected to be in the current directory.
file_path = 'Titanic-Dataset.csv'

# Load the dataset into a pandas DataFrame
try:
    df = pd.read_csv(file_path)
    print(f"Dataset '{file_path}' loaded successfully.")
except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found. Please ensure it's uploaded to the current directory.")
    df = None # Set df to None to prevent subsequent operations from failing

Dataset 'Titanic-Dataset.csv' loaded successfully.

## 2. Dataset Information

Understanding the data types and non-null counts for each column is crucial for identifying potential data quality issues, such as missing values or incorrectly assigned data types. The `df.info()` method provides a concise summary of the DataFrame.

In [74]:
if df is not None:
    print("--- Dataset Information (df.info()) ---")
    # The .info() method prints a summary of the DataFrame, including the index dtype and column dtypes,
    # non-null values, and memory usage.
    df.info()

    print("\nExplanation:")
    print("  - 'PassengerId', 'Survived', 'Pclass', 'SibSp', 'Parch', 'Fare' are integers or floats.")
    print("  - 'Name', 'Sex', 'Ticket', 'Cabin', 'Embarked' are object (string) types.")
    print("  - Notice the 'Age', 'Cabin', and 'Embarked' columns have fewer non-null entries than the total rows (891),")
    print("    indicating the presence of missing values that need to be addressed.")

--- Dataset Information (df.info()) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Explanation:
  - 'PassengerId', 'Survived', 'Pclass', 'SibSp', 'Parch', 'Fare' are integers or floats.
  - 'Name', 'Sex', 'Ticket', 'Cabin', 'Embarked' are object (string) types.
  - Notice the 'Age', 'Cabin', and 'Embarked' columns have fewer non-null entries than the total rows (891),
    indicating the presence of missing values that need to be addressed.

## 3. Statistical Summary

A statistical summary provides key descriptive statistics for numerical columns, offering insights into the distribution, central tendency, and spread of the data. This helps in detecting outliers or unusual patterns.

In [75]:
if df is not None:
    # --- Before Handling Missing Values ---
    print("--- Missing Values Before Handling ---")
    missing_before_handling = df.isnull().sum()
    display(missing_before_handling[missing_before_handling > 0])

--- Missing Values Before Handling ---

Age         177
Cabin       687
Embarked      2
dtype: int64

## 4. Missing Value Analysis

Identifying the exact count and percentage of missing values per column is the first step in deciding an appropriate strategy for handling them. This analysis highlights which columns require attention.

In [76]:
if df is not None:
    # --- Check for duplicate records ---
    initial_rows = df.shape[0]
    duplicates_count = df.duplicated().sum()
    print(f"--- Duplicate Records Before Removal ---")
    print(f"Number of duplicate rows found: {duplicates_count}\n")

    # --- Remove duplicates if present ---
    if duplicates_count > 0:
        df.drop_duplicates(inplace=True)
        print(f"Successfully removed {duplicates_count} duplicate rows.")
    else:
        print("No duplicate rows found to remove.")

    # --- Show before and after counts ---
    final_rows = df.shape[0]
    print("\n--- Duplicate Records After Removal ---")
    print(f"Number of rows after removing duplicates: {final_rows}")
    print(f"Number of duplicate rows remaining: {df.duplicated().sum()}")
    print(f"Total rows removed: {initial_rows - final_rows}")

--- Duplicate Records Before Removal ---
Number of duplicate rows found: 0

No duplicate rows found to remove.

--- Duplicate Records After Removal ---
Number of rows after removing duplicates: 891
Number of duplicate rows remaining: 0
Total rows removed: 0

## 5. Handling Missing Values

Based on the analysis, we will implement strategies to handle missing values professionally:
-   **Age**: Impute with the median, as it's less sensitive to outliers than the mean.
-   **Embarked**: Impute with the mode, as it's a categorical feature.
-   **Cabin**: Drop this column entirely due to a very high percentage of missing values (approximately 77%), which makes imputation unreliable and the column potentially uninformative.

In [77]:
if df is not None:
    print("--- Data Types Before Conversion ---")
    display(df.dtypes)

--- Data Types Before Conversion ---

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

## 6. Duplicate Removal

Duplicate records can lead to biased statistical analysis and machine learning models. This step identifies and removes any exact duplicate rows to ensure the integrity of our dataset.

In [78]:
if df is not None:
    print("--- Column Names Before Renaming ---")
    print(df.columns.tolist())

--- Column Names Before Renaming ---
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

## 7. Data Type Conversion

Optimizing data types can lead to significant memory savings and improved performance for certain operations. Categorical features like 'Sex' and 'Embarked' are best represented with the `category` data type.

In [79]:
if df is not None:
    print("--- Final Dataset Verification ---")

    # Show final shape to confirm row/column changes after cleaning
    print(f"\nFinal Dataset Shape: {df.shape}")

    # Show updated column names
    print("\nUpdated Column Names:")
    print(df.columns.tolist())

    # Display the first 5 rows of the cleaned dataset
    print("\nFirst 5 Rows of Cleaned Dataset:")
    display(df.head())

    # Show final df.info() to confirm data types and absence of missing values
    print("\nFinal Dataset Information (df.info()):")
    df.info()

--- Final Dataset Verification ---

Final Dataset Shape: (891, 12)

Updated Column Names:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

First 5 Rows of Cleaned Dataset:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Final Dataset Information (df.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## 8. Renaming Columns

Renaming columns to more intuitive and consistent names enhances code readability and makes the dataset easier to work with, especially for new collaborators or future analysis.

In [80]:
if df is not None:
    # Define the output file path for the cleaned dataset
    output_file_name = 'Cleaned_Titanic_Dataset.csv'

    # Save the DataFrame to a CSV file. index=False prevents pandas from writing the DataFrame index as a column.
    df.to_csv(output_file_name, index=False)
    print(f"\nCleaned dataset successfully saved as '{output_file_name}'.")
    print("This file is now ready for further analysis or machine learning model development.")

Cleaned dataset successfully saved as 'Cleaned_Titanic_Dataset.csv'.
This file is now ready for further analysis or machine learning model development.

## 9. Final Dataset Verification

After completing all cleaning and preprocessing steps, a final verification is essential to ensure the dataset is in the expected state and ready for downstream tasks such as analysis or model training.

In [81]:
if df is not None:
    print("\n--- Comparison: Before vs. After Preprocessing ---")

    # To show 'before' state, we need to reload the original data or store its initial state
    # For this comparison, let's assume we can reload the original for demonstration purposes
    original_df = pd.read_csv(file_path)

    # Missing Values Comparison
    print("\n--- Missing Values ---")
    print("Before handling:\n", original_df.isnull().sum()[original_df.isnull().sum() > 0])
    print("\nAfter handling:\n", df.isnull().sum()[df.isnull().sum() > 0])

    # Duplicates Comparison
    print("\n--- Duplicate Records ---")
    print(f"Before removal: {original_df.duplicated().sum()} duplicates")
    print(f"After removal: {df.duplicated().sum()} duplicates")

    # Dataset Shape Comparison
    print("\n--- Dataset Shape ---")
    print(f"Before preprocessing: {original_df.shape}")
    print(f"After preprocessing: {df.shape}")

--- Comparison: Before vs. After Preprocessing ---

--- Missing Values ---
Before handling:
 Age         177
Cabin       687
Embarked      2
dtype: int64

After handling:
 Age         177
Cabin       687
Embarked      2
dtype: int64

--- Duplicate Records ---
Before removal: 0 duplicates
After removal: 0 duplicates

--- Dataset Shape ---
Before preprocessing: (891, 12)
After preprocessing: (891, 12)

## 10. Save Cleaned Dataset

Saving the cleaned dataset is a critical step. This ensures that the preprocessing efforts are preserved, allowing for quick access to the prepared data without needing to re-run the entire cleaning pipeline. This `Cleaned_Titanic_Dataset.csv` can then be used for further analysis or model building.